name: Upload Repository as ZIP to Server

on:
  workflow_dispatch: # run manually
  push:              # run on push to main
    branches:
      - main

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r repo.zip .

      - name: Upload to server
        env:
          REPO: ${{ github.repository }} # just the repo name
        run: |
          curl -f -X POST \
            -F "file=@repo.zip" \
            "https://mdq.anb.codes/upload/${REPO}"

